# Generated by Django 6.0.1 on 2026-02-04 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.URLField(blank=True, help_text='Full URL or frontend route'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.product'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
