# Generated by Django 6.0.1 on 2026-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_banner_options_banner_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home_sections/')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Frontend route or full URL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
