# Generated by Django 6.0.1 on 2026-02-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='about/')),
                ('point_1', models.CharField(max_length=200)),
                ('point_2', models.CharField(max_length=200)),
                ('point_3', models.CharField(max_length=200)),
                ('point_4', models.CharField(max_length=200)),
                ('story_label', models.CharField(default='OUR STORY', max_length=100)),
                ('story_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
