# Generated by Django 6.0.1 on 2026-02-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={},
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='homesection',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
