# Generated by Django 6.0.1 on 2026-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='story_label',
            field=models.CharField(default='OUR STORY', max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='story_title',
            field=models.CharField(max_length=2000),
        ),
    ]
