# Generated by Django 6.0.1 on 2026-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_aboutsection_story_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='story_title',
            field=models.TextField(max_length=2000),
        ),
    ]
